import React, { useState, useEffect, useRef } from 'react';

export default function ResearchSummary({ summary, meta }) {
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const intervalRef = useRef(null);

  useEffect(() => {
    if (!summary) return;

    // Reset and start typewriter
    setDisplayedText('');
    setIsTyping(true);

    let charIndex = 0;
    intervalRef.current = setInterval(() => {
      charIndex++;
      if (charIndex >= summary.length) {
        setDisplayedText(summary);
        setIsTyping(false);
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      } else {
        setDisplayedText(summary.slice(0, charIndex));
      }
    }, 8);

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }
    };
  }, [summary]);

  if (!summary) return null;

  const formatTimestamp = (ts) => {
    if (!ts) return '—';
    const d = new Date(ts);
    return d.toLocaleString('en-US', {
      month: 'short', day: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true,
    });
  };

  const getGeneratorBadge = () => {
    const generator = meta.summary_generator || 'gemini';
    if (generator === 'groq') {
      return (
        <span className="text-xs px-2.5 py-1 rounded-full bg-[#10b981]/10 text-[#10b981] border border-[#10b981]/20 font-medium">
          Generated by Groq Llama
        </span>
      );
    } else if (generator === 'gemini') {
      return (
        <span className="text-xs px-2.5 py-1 rounded-full bg-[#8b5cf6]/10 text-[#8b5cf6] border border-[#8b5cf6]/20 font-medium">
          Generated by Gemini Flash
        </span>
      );
    }
    return (
      <span className="text-xs px-2.5 py-1 rounded-full bg-[#64748b]/10 text-[#94a3b8] border border-[#64748b]/20 font-medium">
        {meta.mode === 'pure' ? 'Pure Fuzzy Analysis' : 'Deterministic Fallback'}
      </span>
    );
  };

  return (
    <div className="mb-8 rounded-xl border border-[#6366f1]/30 bg-[#0f0f1e] p-6 transition-all duration-300 animate-[fadeIn_0.3s_ease-in-out]">
      <div className="flex items-center justify-between mb-5 px-3 py-2 rounded-lg" style={{ background: 'linear-gradient(90deg, rgba(99,102,241,0.05), transparent)' }}>
        <div className="flex items-center gap-2">
          <div className="w-1 h-4 rounded-full bg-[#6366f1]" />
          <span className="text-[#6366f1] text-lg">✦</span>
          <h2 className="text-xs font-bold tracking-widest uppercase text-[#8b9bb4]">Research Analysis</h2>
        </div>
        {getGeneratorBadge()}
      </div>
      <div className="max-w-prose">
        <p className="text-[#cbd5e1] leading-relaxed text-base">
          {displayedText}
          {isTyping && <span className="inline-block ml-0.5 text-[#6366f1] font-light animate-pulse">|</span>}
        </p>
      </div>
      <div className="flex items-center gap-2 mt-5 pt-4 border-t border-[#1e1e3a]">
        <span className="text-xs px-2.5 py-1 rounded-full bg-[#161628] border border-[#1e1e3a] text-[#94a3b8]">
          Mode: {meta.mode === 'ai' ? 'AI Enhanced' : 'Pure Fuzzy'}
        </span>
        <span className="text-xs px-2.5 py-1 rounded-full bg-[#161628] border border-[#1e1e3a] text-[#94a3b8]">
          {meta.n_processes} Processes
        </span>
        <span className="text-xs px-2.5 py-1 rounded-full bg-[#161628] border border-[#1e1e3a] text-[#94a3b8]">
          {formatTimestamp(meta.timestamp)}
        </span>
      </div>
    </div>
  );
}
